### ISSUE TITLE
Winging It - 05 FastAPI

### ISSUE THREAD

**Issue by stacyk** [oddbird/oddleventy#472]
**Expert:** Ed
**Co-Host:** James
**Co-Host:** David
**[Show Notes Link](https://docs.google.com/document/d/1kMgMei760zV9EnGULEmehk69wUEHckK6wmm4owf3WWM/edit?usp=sharing)** 
**Recording date:** Jan 30, 2024

## After Recording

**Video File Link (Streamyard):** https://streamyard.com/teams/YziLfq8uRzJe5ObRRuXMcnw8/videos/xwppy5wutrwp

**Title Suggestions for YouTube (and OddSite) Post:** FastAPI: Streamline Your API Development

**Episode Description for YouTube (and OddSite) Post:** Join us for a dynamic exploration of FastAPI, a modern Python framework for API development. We kick off with a clear explanation of FastAPI and its standout features, then move into error handling and data validation. We also delve into OpenAPI’s role in managing endpoints and the perks of automated documentation.

**Chapters:**
Each line includes a 4 digit time stamp and short chapter title.

00:19 What is FastAPI?
01:39 What Makes FastAPI Unique?
02:00 Demo
02:36 Data Validation
05:33 Parsing Errors
08:28 Viewing Endpoints with the OpenAPI Schema
10:40 Automatic Documentation
12:46 OpenAPI Client Generators
15:35 Using OpenAPI Documentation on the Frontend
18:14 Challenges of Using FastAPI
21:17 When to Use FastAPI
23:01 Next Episode: How to Use a JavaScript Proxy as Your Store

**YouTube Episode Link:**
https://youtu.be/1fSRG8_C2ms

**OddSite Post Link:**

---

##  Production Checklist

- [x] Create Title @jerivas 
- [x] Create Description @jerivas 
- [x] Create Video thumbnail
- [x] Create OddSite Hero image
- [x] Create OddSite Post
- [x] Edit video
- [x] Upload Video to YT; add unlisted video link to this issue
- [ ] Review Video https://youtu.be/1fSRG8_C2ms
- [x] Make OddSite Post
- [x] Review OddSite PR
- [ ] Publish video
- [ ] Promote video (on all the socials)
- [ ] Review analytics; how did the topic/desciption/etc do? What can we can learn from these things?

**Comment by stacyk** [comment]
James said: "We could mention the FastAPI to OpenApi to front end client generator, or perhaps spin that off into a separate (mini?) episode."

**Comment by jerivas** [comment]
I just updated the Google Doc with some key questions and responses

**Comment by stacyk** [comment]
@jerivas the show notes look good to me. 

1. Will you will be sharing your screen or showing how something works/looks when developing with FastAPI? 
2. I know James is noted here, do you already have a third person for this episode? Once we settle on the third, then we can schedule something.

**Comment by jerivas** [comment]
> 1. Will you will be sharing your screen?

I think so, that makes it more interesting. Not a demo per se, just something to look at.

> 2. Do you already have a third person for this episode?

I think @dvdherron could find this interesting. Would you like to join us, David?

**Comment by dvdherron** [comment]
> > 1. Will you be sharing your screen?
> 
> I think so, that makes it more interesting. Not a demo per se, just something to look at.
> 
> > 2. Do you already have a third person for this episode?
> 
> I think @dvdherron could find this interesting. Would you like to join us, David?

Always down to learn. Count me in @jerivas!

**Comment by dvdherron** [comment]
Could someone with StreamYard admin access upload the episode 5 files to google drive? Thanks! (cc @SondraE @stacyk)

**Comment by dvdherron** [comment]
@stacyk @SondraE @jamesnw @jerivas Here's a rough first edit of Episode 05. 

https://www.dropbox.com/scl/fi/hxh31aszrc4k9bcf48sup/Winging-It-Episode-05-Fast-API_V1_01.mov?rlkey=vss2re9irhevwqi8ohz5mj5iz&dl=0

Is it just me or does it seems like the audio sync is slightly off, most noticeable with Ed's video? I thought it was something happening in the editing software but the raw footage from Streamyard appears to be synced in a similar way.

**Comment by jerivas** [comment]
Do you have a specific timestamp where it's noticeable? I watched a few seconds here and there (both the original stream and the edited version) and nothing jumped out to me. Maybe I'm used to laggy audio from BT headphones 😅

**Comment by jamesnw** [comment]
I'm not bothered by the audio in this. 

At 22:51, I pause to take a drink, I think that can be cut out :-). Besides that, I think it looks great! Nice edit.

**Comment by dvdherron** [comment]
Ok, maybe I'm overthinking this :) Rewatching the edit today it doesn't seem as off as I thought. Could've been just how playback looked in the editing program. 

I'll edit out James's drink and add make some other minor adjustments. Thanks for the feedback!

**Comment by dvdherron** [comment]
Here's the link to the latest edit of Episode 05 @stacyk @sondra (cc @jamesnw @jerivas). I added the chapter timestamps above and also inserted them into the video file itself. If anyone sees anything strange, let me know. 

https://www.dropbox.com/home/OddBird/oddbird%20%3A%20oss%20projects/winging%20it/e5%20FastAPI/Edits?preview=Winging+It+Episode+05+Fast+API_V1_03.mov

The file ending with `V1_03` is the latest version.

**Comment by SondraE** [comment]
@dvdherron The video V1_03 looked good to me!
The only minor thing was that at 22:52, the view switches from the Winging It logo with a link to Winging It on OddSite, to the Winging It logo without a link. I don't think you'd need to switch there. You could just have the view with logo and link continue until you switch back to the view of the people. Not a big deal, though.

**Comment by dvdherron** [comment]
> @dvdherron The video V1_03 looked good to me! The only minor thing was that at 22:52, the view switches from the Winging It logo with a link to Winging It on OddSite, to the Winging It logo without a link. I don't think you'd need to switch there. You could just have the view with logo and link continue until you switch back to the view of the people. Not a big deal, though.

Good catch @SondraE . One of the transitions was off. Fixed in [V1_04](https://www.dropbox.com/scl/fi/w3vf7iu7fvilpszzmtokt/Winging_It_Episode_05_V1_04.mov?rlkey=2icf77tooajs0zqje7y24kkpr&dl=0)
