### ISSUE TITLE
Use <lite-youtube> for youtube embeds

### ISSUE THREAD

**Issue by stacyk** [oddbird/oddleventy#482]
See https://www.zachleat.com/web/youtube-embeds/

https://github.com/paulirish/lite-youtube-embed

The article recommends wrapping the embed in `is-land`, which would give us lazy loading, and even further decrease the initial page load. 

I think the benefits for page load are worth considering. The cost would be the additional dependencies, but neither lite-youtube-embeds or is-land have their own dependencies.

A brief comparison of https://oddbird.ing/2017/01/31/css-day/, which has 7 videos.

Current: 

![Image](https://github.com/oddbird/oddleventy/assets/167908/22301ea9-491c-4f19-b109-20575e2608cd)

With `is-land` set to `on:visible` and `lite-youtube-embed`-

![Image](https://github.com/oddbird/oddleventy/assets/167908/bd88c840-7d91-4ab0-b18b-eb93535ab359)

That's a fairly significant difference.

**Comment by jgerigmeyer** [comment]
Assigning to @jamesnw to merge or clarify what's remaining.
