### ISSUE TITLE
Winging It - 06 Proxy State

### ISSUE THREAD

**Issue by jamesnw** [oddbird/oddleventy#507]
**Expert:** James
**Co-Host:** Stacy
**Co-Host:** Sondra
**Show Notes Link:** https://docs.google.com/document/d/1x4MfnNBuCbInrRmEpgRqddUmQmUuQKbUUcBRBkJGmFg/
**Recording date:** April 17, 2024

## After Recording

- **Video File Link (Streamyard):**
- **YouTube Episode Link:** https://youtu.be/gs94cnKXHh4
- **OddSite Post Link:** https://deploy-preview-565--oddleventy.netlify.app/2024/04/18/winging-it-06/

**Title Suggestions for YouTube (and OddSite) Post:**

**Episode Description for YouTube (and OddSite) Post:**

**Chapters:**
Each line includes a 4 digit time stamp and short chapter title.

00:00:17 What is state?
00:02:59 State management solutions
00:03:41 Javascript and load time
00:05:32 What are Proxies?
00:08:40 How to use Proxies demo
00:17:21 When to use Proxies
00:18:09 Proxies use cases
00:23:07 When to avoid using Proxies
00:24:26 Proxies in the real world

---

## Production Checklist

- [x] [Create Video thumbnail](https://www.dropbox.com/scl/fi/46qduwbgrq1z294yaoad3/winging-it-thumbnail-template.psd?rlkey=7i5yf7uw4o3960nk0kt4c80bq&dl=0) for YouTube
- [x] [Create OddSite Hero image](https://www.dropbox.com/home/OddBird/oddbird%20%3A%20oss%20projects/winging%20it/thumbnails)
- [x] Create OddSite Post
- [x] Edit video
- [x] Upload Video to YT; add unlisted video link to this issue
- [ ] Review Video
- [x] Make OddSite Post
- [ ] Review OddSite PR
- [ ] Publish video
- [ ] Promote video (on all the socials)
- [ ] Review analytics; how did the topic/description/etc do? What can we can
  learn from these things?

**Comment by stacyk** [comment]
Here are my social links so far: 
- [LinkedIn](https://www.linkedin.com/posts/stacykvernmo_managing-state-with-proxies-activity-7186844881774903297-rWeM?utm_source=share&utm_medium=member_desktop)
- [X](https://twitter.com/stacykvernmo/status/1781078806289133767)

**Comment by jamesnw** [comment]
And mine-
- [Mastodon](https://elk.zone/mastodon.cloud/@Jamessw/112298671628554877)
- [LinkedIn](https://www.linkedin.com/posts/jamessw_managing-state-with-proxies-activity-7187115681736278017-ZMqv?utm_source=share&utm_medium=member_desktop)
