### ISSUE TITLE
We shouldn't need to elide summary text, it should be short

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/oddleventy#534]
I noticed that several of our summaries are being cut off with ellipsis - including all three summaries on our 'services' page. I think we should really avoid this. The point of a summary is that it should be short description of the page content that we can use _instead of using automated elision from the page content_. If we need our summaries to be shorter, we should write shorter summaries.

**Comment by mirisuzanne** [comment]
It looks like I may have introduced this first in the post layout (8b2b589), and then in the work samples (756467a), and it got copied into services more recently. I regret it. Does anyone mind if I remove this? And if we see long summaries causing a problem, we can fix the summary instead of cutting it off?

**Comment by SondraE** [comment]
@mirisuzanne Sounds good to me!
