### ISSUE TITLE
Review OddSite posts and identify which ones are good candidates for getting updates

### ISSUE THREAD

**Issue by SondraE** [oddbird/oddleventy#536]
## TO UPDATE

These are select articles in the top 20 for the last 12 months on OddSite. For each one, are there short updates (a paragraph or short video) that could/should be made? Alternatively, are there new articles or videos that could be made on the same topic and linked together?

Any of these that should get updates can be converted into issues.

- [x] @mirisuzanne [Containment on root](https://www.oddbird.net/2023/07/05/contain-root/#containment-and-propagation-(according-to-spec))  
- [ ] #576
- [x] @jerivas [Headed Playwright in Docker](https://www.oddbird.net/2022/11/30/headed-playwright-in-docker/) - Are there any updates that would be useful for this article? 
- [ ] #574
- [ ] #575
- [ ] @mirisuzanne @dvdherron @stacyk [Cascade Layers Polyfill](https://www.oddbird.net/2022/06/21/cascade-layers-polyfill/) - This is an article Sana wrote that's popular. Are there brief updates we could add here? [GH Card](https://github.com/orgs/oddbird/projects/13/views/1?pane=issue&itemId=61492555)
- [ ] @stacyk [Initial Letter](https://www.oddbird.net/2017/01/03/initial-letter/) - Are there any brief updates that would make sense to add to this article?  [GH Card](https://github.com/orgs/oddbird/projects/13/views/1?pane=issue&itemId=61492277)

**Comment by SondraE** [comment]
## TO UPDATE

- Miriam - Containment on root

**Comment by mirisuzanne** [comment]
@SondraE For mixins we need a new post, I think that belongs in a different issue.

**Comment by SondraE** [comment]
Everything in this card's list has its own separate card and/or PR.
