### ISSUE TITLE
Clean up design of CSS Workshop page so that it's more skimmable

### ISSUE THREAD

**Issue by SondraE** [oddbird/oddleventy#538]
@mirisuzanne Ready for review/implementation
[Figma File Design Proposal](https://www.figma.com/file/iQN05m0jxjl60M6qpEjMW4/Cascading-Style-System-Workshop?type=design&node-id=1-11&mode=design&t=gVd49aCSy1KaAY1v-0)

**Comment by mirisuzanne** [comment]
@SondraE Do we already have a grid of content with icons somewhere, or is the longer icon-list on the planning page the closest we have? It's not hard to do, just want to know if we've already built it.

Also: do you know if we have all those icons in the codebase already?

**Comment by mirisuzanne** [comment]
@SondraE I posted a first pass at the design, and documented some of the main content questions we need to address before we finish and merge. Feel free to take a look. I imagine we'll address some of those questions after the meeting tomorrow.

**Comment by SondraE** [comment]
@mirisuzanne 
>Do we already have a grid of content with icons somewhere, or is the longer icon-list on the planning page the closest we have? It's not hard to do, just want to know if we've already built it.

No, I don't believe we already have the grid of content icons elsewhere. 

>Also: do you know if we have all those icons in the codebase already?

We don't necessarily have all those icons in our codebase. Here they are:
![0222-medal-empty](https://github.com/oddbird/oddleventy/assets/8933115/1bf99f38-daf5-471f-a69f-b3655465524a)
![0258-camera-play](https://github.com/oddbird/oddleventy/assets/8933115/06e0fe2c-b862-4fb1-b612-c1f5e46d23b1)
![0292-users2](https://github.com/oddbird/oddleventy/assets/8933115/5b94fe02-ed3a-45e7-a57c-91c88f788bd4)
![0472-bubbles](https://github.com/oddbird/oddleventy/assets/8933115/7700d7b4-623e-4f9a-a7f3-9909231530db)
![0718-mic2](https://github.com/oddbird/oddleventy/assets/8933115/dab8a8e0-a3fb-4adc-a5e5-cb2556d6dbd1)
![0960-hand](https://github.com/oddbird/oddleventy/assets/8933115/ba6c15df-254c-4b70-9e27-9c028e9fe487)

**Comment by SondraE** [comment]
@mirisuzanne Todos after talking with Pland

- [ ] Remove pricing from page, instead invite people to sign up for an initial call
- [ ] Add edited video
- [ ] Add certificate of completion
- [ ] Remove number of session and activities
- [ ] Remove office hours
- [ ] Remove confs and individuals (focus on companies)
- [ ] The second CTA is the form and subsequent CTAs link to it in page
- [ ] Try to get more quotes from attendees

**Comment by mirisuzanne** [comment]
@SondraE What fields should the form have? I imagine we want name/email. But then…

- Company?
- Do we want any longer-form 'tell us more' sort of textarea? If so, what's the label?

I imagine we want to keep it short. But I'm not sure what info we need here.

**Comment by mirisuzanne** [comment]
@SondraE Also: do we have a company Calendly or similar, if we're providing that as an option as well?

**Comment by mirisuzanne** [comment]
I removed the bullet point with a number of sessions and activities. But I left the '5 sessions' language down where we provide an outline. Unless we want to remove the outline entirely, and rely on bullet points instead?

**Comment by SondraE** [comment]
> What fields should the form have?

Name, Email, Message
I think keep it simple and open because we'll want to find out date/time, company, location, number of participants, and more during a conversation with the contact person. Also because we don't yet know what info the contacts will have when they first reach out. We wouldn't want to deter them from contacting us for any reason.

> Do we have a company Calendly or similar, if we're providing that as an option as well?

I have a free Calendly account that is currently linked in the footer of OddSite. https://calendly.com/oddbird/discovery The free version can only have one type of event and a single user's calendar integrations. Perhaps you could get a free version of calendly for yourself if you will be the contact person talking to the people who want to book this workshop. Or we could upgrade from free to $10/seat/month and use the same Calendly account. Or I could do the initial calls and simple collect the information in a doc that has a standard set of questions, but that may not work as well because they probably want to talk directly to the expert that will lead the workshop.

> Unless we want to remove the outline entirely, and rely on bullet points instead?
I prefer the outline to more bullet points. And I found in my brief review that other people include outlines on their workshop marketing pages.

**Comment by SondraE** [comment]
@mirisuzanne 
For icons:

Mic (or Hand?) - Interactive
Bubbles - Q&A
Ribbon - Certificate
Light bulb (or rocket or beaker or W3C logo?) - Cutting Edge 

Here's the SVG for the light bulb: 
![0445-lamp](https://github.com/oddbird/oddleventy/assets/8933115/ba2db455-c289-46f3-a323-5f37bd22827d)
