### ISSUE TITLE
Add missing clients to Work

### ISSUE THREAD

**Issue by SondraE** [oddbird/oddleventy#539]
## Add Pages

- [x] Sass - add playground and website
- [x] GSM - add
- [x] Google - Flesh out info on the Google Chrome project @mirisuzanne 
- [x] Sass - Review Sass project content that James contributed @SondraE    

## Checklist

- [ ] Get quote and pic from Ryan @SondraE _(followed up April 15)_
- [x] Get quote (about design systems & Google) and pic from Nicole @mirisuzanne
- [x] Add logos to front page @SondraE 
- [x] Get quote and pic from Natalie @mirisuzanne 
- [x] Blurb about what we did and tools/languages we used for Sass project @jamesnw

**Comment by jgerigmeyer** [comment]
Along with the Sass website/playground, I think we could also mention the features we built for Sass itself: Color 4 support, pkg imports, calculations api, and shared processes.

**Comment by mirisuzanne** [comment]
I reached out to Natalie for quotes. I didn't work on the Sass projects much, so @jgerigmeyer might know more about the tools/languages involved. I agree we should include our contributions to the language as well - maybe as a separate project for the same client?

**Comment by SondraE** [comment]
**Natalie Quotes:**

"Oddbird rewrote http://sass-lang.com/ from the ground up to make it easier to work on, update, and deploy. Not only that, they added a new online playground and got Sass running in the browser to power it. They're a fantastic team that we were lucky to work with."

"Oddbird’s work on Sass helped power out several new Sass features that would have taken the core team alone years longer to make. They dropped in like a task force, learned the ropes of programming language design and development, and made substantial improvements to the product. We’d love to work with them again!"

Using her CoHost avatar: https://cohost.org/nex3

**Comment by jgerigmeyer** [comment]
@jamesnw Would you be willing to draft a summary of the work we did for Google on [Sass](https://github.com/oddbird/oddleventy/pull/540/files#diff-bd3a9672e5714acb437706da0fa1bf3e1a8941d6076395e0679f07fd89dad796) and [Sass Site](https://github.com/oddbird/oddleventy/pull/540/files#diff-d5ec8be19a0d13f89a552691ef0b62f2131c01b113f17c403284400a2c9d9db2)? (It's looking unlikely that I'll be able to get to it before I head out for a week of vacation.)

**Comment by SondraE** [comment]
@mirisuzanne 
I'm assigned (above) to add logos to the homepage for clients we're adding to OddSite.
Should I add the Chrome logo and/or the Google logo? 
For Sass, should I add the same Sass logo we use in the OddTools section to the client work section, or is there some other version of the Sass logo that would make sense to have here?

**Comment by mirisuzanne** [comment]
Decisions:

- We'll use the Google logo, and list Google as the client for all three projects
- That will replace the Phamaly logo on our home page

**Comment by mirisuzanne** [comment]
@SondraE I fleshed out the UI Fund page, and added some quotes from other big names in the community. (I reached out to Nicole again as well, but don't think we should let that block us).

**Comment by mirisuzanne** [comment]
> Working with Miriam and her team is a force multiplier for my engineering team. We ship higher quality APIs much faster than we had before. We keep our C++ engineers working on what only they can do, and Miriam fills in all the blanks. Developers who use our APIs are so happy with the results, even calling it a renaissance of CSS. Oddbird is a company I recommend without reservation. They are among the best in the world at front end, design systems, and w3c standards.
> 
> Their communication is also excellent. They come prepared, they are deeply technical, and they can express complex concepts to a variety of audiences. I have invited them to meetings with execs, designers, engineers, and our own customers. They always do a great job representing the project.
> 
> Oddbird is easily among the best companies in the world at building design systems.
