### ISSUE TITLE
Update article: containment on root

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/oddleventy#571]
[Can We Query the Root Container?](https://www.oddbird.net/2023/07/05/contain-root/#containment-and-propagation-(according-to-spec))

**Comment by SondraE** [comment]
@mirisuzanne If you have a moment to post something short about the updates on querying the root container, can you let me know and I'll repost on OddBird's accounts?

**Comment by mirisuzanne** [comment]
@SondraE https://front-end.social/@mia/112434952972064199

**Comment by SondraE** [comment]
@mirisuzanne 
https://www.linkedin.com/feed/update/urn:li:activity:7195861405818916864/
https://twitter.com/OddBird/status/1790097689398395334
