### ISSUE TITLE
Script & film workshop welcome video

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/oddleventy#597]
See also: https://github.com/orgs/oddbird/projects/10/views/1?filterQuery=is%3Aissue+video&pane=issue&itemId=57266354

- [x] script it
- [x] film it
- [x] draft edit
- [x] @SondraE review
- [x] @stacyk review
- [x] @SondraE thumbnail review/approve/make public

**Comment by mirisuzanne** [comment]
@SondraE I'm feeling a bit torn on the target audience here. You left a lot of notes on the previous one, for how to focus it more towards CTO's. Which is maybe specifically trying to pitch it to companies?

My sense generally is that we _first_ have to get developers interested, and then make sure it's something _they can sell_ to their CTOs (or whoever approves budget for education). Especially for hosted workshops like this one, where it's not company specific? So I might try to keep it addressed _to developers_ (in terms of second-person address) while working in some of the team pain points? Thoughts?

**Comment by mirisuzanne** [comment]
But also I don't know if we're planning different videos for self-hosted vs smashing vs selling to companies?

**Comment by mirisuzanne** [comment]
This is a rough first draft that I know is missing things, and still not funny - but a template to start from: 

> Web Layout has a long history of frustrating limitations, hacks, and unexpected behavior. If CSS is so awesome, why does text just honk right out of the box like that? Many teams are still using outdated workarounds that require extra time, effort, and external tools – for a less reliable result. It doesn't have to be like that.
> 
> I'm Miriam Suzanne, one of the founders here at OddBird, where we help companies pursue large-scale projects – building more resilient and maintainable web applications and design systems. 
> 
> I'm also part of the CSS Working Group, helping develop new CSS features like container queries, cascade layers, and scope.
> 
> Together, OddBird and I developed this workshop to help your team get up-to-speed with the latest in CSS Layout techniques. In three practical sessions, we'll go beyond the syntax – so you understand exactly what's happening in the browser, and why you might choose flexbox vs grid for different use-cases.

(I really like starting with the topic rather than qualifications. It feels a lot more to-the-point.)

**Comment by SondraE** [comment]
@mirisuzanne I really like this!
- I like how short and to the point this draft is.
- I think the message in your first and last paragraphs is clear and appealing to both developers and to CTOs! A+
- I like how you mentioned OddBird's primary service in your explanation of who we are.

If you remove the word _three_ from the phrase _three practice sessions_, I think you could use this same video to promote the self-hosted and company versions of this workshop.

You could consider adding something like this to the final paragraph to make sure you're still speaking to both devs and CTOs.
_Together, OddBird and I developed this workshop to help your team get up-to-speed with the latest in CSS Layout techniques -- improving team workflow and giving your users a more consistent, delightful experience._

Ideas I added to the [previous card](https://github.com/orgs/oddbird/projects/10/views/1?filterQuery=is%3Aissue+video&pane=issue&itemId=57266354) that were specifically for CEOs/CTOs around pain points, outcomes, and benefits could be used on the page we created for companies. And/or they could go in social media posts.

**Comment by mirisuzanne** [comment]
Ok, here's the first draft edit: 

https://www.dropbox.com/scl/fi/b9b0lqkwlnvsu2i00g4do/layout-workshop-intro.mp4?rlkey=rq94kn4erp9oj2ksyr98lgfnw&dl=0

I think it would be great to get some sound over the final animated bumper (if we want to keep it). But I'm not sure that should hold us up? We do probably want to add captions when we publish.

@SondraE @stacyk I imagine this would go on the youtube channel, and then get embedded in the page as well?

**Comment by mirisuzanne** [comment]
(updated to improve the outro, without needing sound)

**Comment by SondraE** [comment]
@mirisuzanne That looks really good! Ship it. 
Yeah. I assume YT first, and then the workshop page.

**Comment by stacyk** [comment]
Loved it. Loved the outro, great message, delivery and great shots you mixed in with it. Uploading now

**Comment by stacyk** [comment]
OK, it is unlisted as of now until I get confirmation on thumbnail, but here it is: https://youtu.be/9EDOzJJdxWA?si=93Pu47PSFE-QvdoP

@SondraE feel free to edit the description or thumbnail, etc. and then make sure to mark it as public once you approve.

**Comment by SondraE** [comment]
@mirisuzanne I reviewed and made it public. The video can now be added to OddSite and shared socially.

**Comment by mirisuzanne** [comment]
Shared on mastodon and linkedin

**Comment by SondraE** [comment]
Reposted and also shared elsewhere too.

**Comment by mirisuzanne** [comment]
Put it on bluesky as well. Not very active there, so we'll see.
