### ISSUE TITLE
Update Talks/Workshop intro to focus on "register now" CTA

### ISSUE THREAD

**Issue by SondraE** [oddbird/oddleventy#598]
[Pull Request 601](https://github.com/oddbird/oddleventy/pull/601)

- [x] Update header image
- [x] Add og image for social posts
- [x] Update register now to go to registration on OddSite
- [x] Change banner text from "Featured Workshop" to "Upcoming Workshop"
- [x] Add blurb near the bottom about the fact that we offer a scholarship or discount based on need

**Comment by SondraE** [comment]
@stacyk @mirisuzanne I made the updates listed in this card, but I have a question. For the _update image_ bullet point, if I remember right, we wanted to change the header image to an image that would work well for social posts, right, to solve the problem that an image uploaded to social cannot be a link? I realized that the image I want to appear on social posts has all the same information (title, subtitle, date/time) that is already on the oddsite post, so it ends up looking strange. Is there a way to designate a specific social card image instead of having the post header image be the default image that shows up on social media? Is it complicated and time consuming to set that up? Should we forget about this idea and just stick with uploading an image of our social card and putting a link to the oddsite page in the social post body?

<img width="1440" alt="Screenshot 2024-05-24 at 3 59 13 PM" src="https://github.com/oddbird/oddleventy/assets/8933115/13b6c2a5-e9c5-45ad-8433-c1424f032cfa">

**Comment by mirisuzanne** [comment]
@SondraE In the yaml metadata at the top of the page, you can set a different image for the open-graph data and the header:

```yaml
# the header image needs a src file & alt text
image:
  src: path/to/header-img.jpg
  alt: Description of image
# open-graph image doesn't get alt text
og:
  img: path/to/og-img.jpg
```

Weird that we use both img & image here, but we can fix that naming in a different story.
