### ISSUE TITLE
Re-make or reuse a Mozilla grid or subgrid or both video using existing demo

### ISSUE THREAD

**Issue by SondraE** [oddbird/oddleventy#604]
https://www.oddbird.net/2019/10/18/grids/
https://www.oddbird.net/2019/10/16/subgrid-forms/
https://www.oddbird.net/2019/10/15/subgrid-cards/

- [x] Mia check these videos for accuracy
- [x] @mirisuzanne Add workshop CTA to these video pages
- [x] @SondraE Share on social (June 10)
- [x] @stacyk Share on social (June 12)
- [x] @stacyk Share on social (June 14)

**Comment by mirisuzanne** [comment]
@SondraE these videos are still accurate (though we now have full browser support). My ego wants to make new better versions of them, but I expect that's not a priority.

**Comment by SondraE** [comment]
@mirisuzanne I don't recall whether you were planning to do the rest of the work on this card or if I was.

**Comment by mirisuzanne** [comment]
@SondraE either way. I won't get to it today, but we could talk about it tomorrow morning.

**Comment by SondraE** [comment]
@mirisuzanne 
Would something like this work for the social posts?
And do you think I should include in the post something like, "If you want to dive deeper into grid and subgrid, come join us for a Cascading Layouts Workshop June 24-26, 2024." Or would that feel too salesy and turn developers away? Would it be better to just let them find the workshop info once they navigate to OddSite?

**Post 1**
Learn how to build some previously-complex layouts in under 10 minutes using #CSS Grid and Subgrid.
For years, we’ve struggled to build resilient layouts on the web, but CSS Grid and Subgrid changes all that. You can learn how to start using these tools now with Miriam Suzanne (there's full browser support!) with only a few properties and basic concepts.
https://www.oddbird.net/2019/10/18/grids/

**Post 2**
It’s a common pattern to align form labels and inputs in grid-like layout. In this tutorial, Miriam Suzanne demonstrates how to do it quickly using #CSS subgrid, with several quick fallbacks.
https://www.oddbird.net/2019/10/16/subgrid-forms/

**Post 3**
Card layouts are popular on the web, rows and columns of boxes with similar content. #CSS grids can help align those cards, but it’s still be hard to line-up content inside the cards – headers and footers that might need more or less room. Learn how to use Subgrid for better card layouts with Miriam Suzanne.
https://www.oddbird.net/2019/10/15/subgrid-cards/

**Comment by mirisuzanne** [comment]
- I think these posts are fine, yes
- I would maybe note that the videos are old, but still relevant?
- I would absolutely include the workshop details. It's the only reason to be sharing 4-year old videos 😅

**Comment by SondraE** [comment]
Idea:
Use screenshot showing before and after as the post image for Post 3.

**Comment by SondraE** [comment]
@mirisuzanne @stacyk @davisagli 
**Post 1 to boost on the socials**:
https://www.linkedin.com/feed/update/urn:li:activity:7206063249581109248/
https://front-end.social/@OddBird/112594720407315030
https://x.com/OddBird/status/1800301060797665674

**Comment by stacyk** [comment]
Post 3 to boost on the socials (although David Glick is optional :) :
https://x.com/stacykvernmo/status/1800971062869623020
https://www.linkedin.com/posts/stacykvernmo_css-activity-7206737585073770496-3YCO/
https://front-end.social/@stacy/112605283235694849

**Comment by SondraE** [comment]
Boosted Post 3

**Comment by stacyk** [comment]
Post 2:
https://x.com/stacykvernmo/status/1801725286641451042
https://www.linkedin.com/posts/stacykvernmo_laying-out-forms-using-subgrid-activity-7207491228668448769-KRhz
https://front-end.social/@stacy/112617054649378073
