### ISSUE TITLE
Create a Mixins video and/or post

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/oddleventy#618]

**Comment by mirisuzanne** [comment]
@SondraE I suppose #614 is related to this, though not what I originally had in mind. Maybe I'll use this card for this post, and can open a new one for actual updates as browsers start to implement (more likely functions before mixins).

**Comment by SondraE** [comment]
@mirisuzanne I reviewed and merged. Do you want to post on Mastodon and LinkedIn first and I boost on OddBird or would you prefer that I create a post to share this directly on OddBird's socials?
