### ISSUE TITLE
A blog post updating on Anchor Position

### ISSUE THREAD

**Issue by jamesnw** [oddbird/oddleventy#646]

**Comment by jamesnw** [comment]
Mastodon-

https://elk.zone/mastodon.cloud/@Jamessw/112717824542708498

**Comment by SondraE** [comment]
Added update to OddBird Open Source on Open Collective

<img width="1355" alt="Screenshot 2024-07-02 at 1 24 33 PM" src="https://github.com/oddbird/oddleventy/assets/8933115/fab89e18-c911-4b25-ac90-25122ae8cdf4">
